version: 1.0.{build}
environment:
  matrix:
    # array of all environments used to test builds
    - GENERATOR: Visual Studio 14 2015
      CFG: Debug
#      disabled until repo also includes 64-bit library link stub
#    - GENERATOR: Visual Studio 14 2015 Win64
#      CFG: Debug
#      extcode.h does not recognize this architecture
#    - GENERATOR: Visual Studio 14 2015 ARM
#      CFG: Debug

cache:
  - "%LocalAppData%\\pip"
#  - "C:\\Python27\\Lib\\site-packages"

# Workaround for http://help.appveyor.com/discussions/problems/4569
before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
    # enable calling pip directly
  - cmd: set PATH=%SystemDrive%\Python27\Scripts;%PATH%
  - cmd: pip install autobahntestsuite
  - cmd: wstest --autobahnversion
  - cmd: cmake --version
  - cmd: git submodule update --init
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" -DFTW_LVIDE_PATH="../.ci" ../kernel
  - cmd: cmake --build .

test_script:
  - cmd: ctest --output-on-failure --build-config "%CFG%" .
